redis:
  host: localhost
  port: 6379
  db: 0
  max_connections: 50
  socket_timeout: 5
  socket_connect_timeout: 3
  retry_on_timeout: true
  health_check_interval: 30

cache:
  default_ttl: 3600  # 1 hour
  max_memory: "2gb"
  eviction_policy: "allkeys-lru"
  max_model_size: "500mb"

queues:
  task_queue:
    max_length: 10000
    batch_size: 100
    processing_timeout: 300

monitoring:
  metrics_enabled: true
  metrics_interval: 60
  alert_threshold: 0.9