# gpu-faas-scheduler/tests/test_config.yaml
test_environment:
  num_gpus: 4
  gpu_memory: 16384  # 16GB per GPU
  models:
    - id: "model1"
      size: 2048
      load_time: 2.5
      exec_time: 1.2
    - id: "model2"
      size: 4096
      load_time: 3.5
      exec_time: 1.5
    - id: "model3"
      size: 8192
      load_time: 4.2
      exec_time: 2.0